pipeline {
    agent any
    stages {
        stage('Build'){
             steps {
                 sh script: '''
                     echo "I am in Test step"
                     chmod +x ./gradlew
                     ./gradlew build
                 '''
             }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                '''
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                '''
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                '''
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage ="
                '''
            }
        }
    }
}
