pipeline  {
    agent any
    stages  {
        stage('Build')  {
            steps  {
                sh script: '''
		echo "Building Stage"
		chmod +x ./gradlew
		./gradlew build -x test
		''',
		label: "Build"
            }
        }
	stage('Test')  {
	    steps  {
		sh script: '''
		echo "Testing Stage"
		./gradlew test
		''',
		label: "Test"
	    }
	}
	stage('Build Docker')  {
	    steps  {
		sh script: '''
		docker build -t "merchantgalaxy" -f .infra/docker/Dockerfile .
		''',
		label: "Build docker image"
	    }
	}
	stage('Publish Docker Image')  {
	    steps  {
		sh script: '''
		docker login -u dhvani2510 -p hjdj@0389
		docker tag merchantgalaxy:latest dhvani2510/merchant_galaxy:latest
		docker push dhvani2510/merchant_galaxy:latest
		''',
		label: "Publish"
	    }
	}
    }
}
